worker_processes 1;
events { worker_connections 1024; }
http {
  include mime.types;
  sendfile on;

  server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    # Allow replacing inside HTML/CSS/JS
    sub_filter_types text/html text/css application/javascript;
    sub_filter_once off;
    # Strip the origin so absolute links become local paths
    sub_filter 'https://halldweb.jlab.org' '';
    sub_filter '//halldweb.jlab.org' '';

    location / { try_files $uri $uri/ $uri.html =404; }
    autoindex on;
    location ~* \.(php|cgi|pl|sh|py)$ { return 403; }
  }
}

